-- Remove SÓ os três clientes de demonstração e tudo o que lhes pertence.
-- Ordem inversa das dependências: filhos primeiro.
BEGIN;
DELETE FROM "Appointment"    WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Service"        WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Professional"   WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Certification"  WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "VehicleLog"     WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Vehicle"        WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "LivestockEvent" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "LivestockBatch" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "SiloMovement"   WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Contract"       WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Silo"           WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "IrrigationEvent" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "PlotApplication" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "SoilAnalysis"   WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Plot"           WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Employee"       WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Harvest"        WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "AuditLog"       WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "JournalLine"    WHERE "journalEntryId" IN (SELECT id FROM "JournalEntry" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic')));
DELETE FROM "JournalEntry"   WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "OrderItem"      WHERE "orderId" IN (SELECT id FROM "Order" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic')));
DELETE FROM "Order"          WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Payment"        WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "InventoryMovement" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "InvoiceItem"    WHERE "commercialInvoiceId" IN (SELECT id FROM "CommercialInvoice" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic')));
DELETE FROM "CommercialInvoice" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "WarehouseStock" WHERE "warehouseId" IN (SELECT id FROM "Warehouse" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic')));
DELETE FROM "Timbrado"       WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "ExchangeRate"   WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Supplier"       WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Customer"       WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Product"        WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Warehouse"      WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Permission"     WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Account"        WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "PasswordSetupToken" WHERE "userId" IN (SELECT id FROM "User" WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic')));
DELETE FROM "User"           WHERE "tenantId" IN (SELECT id FROM "Tenant" WHERE slug IN ('demo-store','demo-farm','demo-clinic'));
DELETE FROM "Tenant"         WHERE slug IN ('demo-store','demo-farm','demo-clinic');
COMMIT;
